### ISSUE TITLE
Is there any way to pass request parameters that will be returned?

### ISSUE THREAD

**Issue by xgp** [bihe/ninja-oauth-google#2]
I'd like to pass a random "state" parameter that will get returned to the callback in order to prevent request forgeries. Is there any way using this module or pac4j that I can pass an arbitrary parameter that will get returned in the callback.

This is similar to what is described here: https://cloud.google.com/java/getting-started/authenticate-users

**Comment by bihe** [comment]
The request paramter (state) is submitted by pac4j implicitly. This is the reason why the NinjaWebContext class is implemented to provide the possibility to store the state parameter in the session.
e.g.:  https://github.com/pac4j/play-pac4j/issues/66

You do not need to check the state parameter yourself - this is the task of pac4j. You can try it out by
_forcing_ setSessionAttribute/getSessionAttribute to NOT store attributes in session. Then you will receive an error during callback.

By_the_way: Updating the versions on this module is long overdue ;)

**Comment by xgp** [comment]
Thanks! I like it when the answer is that it's already done.

I'll update versions and submit a pull request.
